### ISSUE TITLE
Looks like the github-readme-linkedin.vercel.app errors out

### ISSUE THREAD

**Issue by MrCsabaToth** [ssoroushhh/ssoroushhh#1]
I had to remove it from my GitHub profile

**Comment by soroushchehresa** [comment]
@MrCsabaToth Thanks for the report.
This error happens to LinkedIn token limits. you can fork this project and [deploy it to your own Vercel instance](https://github.com/soroushchehresa/github-readme-linkedin#deploy) with your LinkedIn token to use this project without any errors.
However the error fixed for now, but it seems to happen again!
